[package]
name = "my_diceware"
version = "0.1.0"
authors = ["alvise <alvisebruniera@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake2 = "0.9.1"
rand_distr = "0.4.0"
rand = "0.8.0"
